# Lab 3 Notes

## Printing out the value of a variable in Python

In [1]:
n = 3

In [7]:
str1 = 'The number is '
str2 = str(n)
str3 = str1 + str2
print(str3)

The number is 3


In [8]:
print(str1, str2)

The number is  3


In [9]:
print(str1, n)

The number is  3


### Python f-strings

In [11]:
n = 3
print('the number is: n')

the number is: n


In [12]:
print(f'the number is: {n}')

the number is: 3


In [13]:
print('the number is: {n}')

the number is: {n}


In [15]:
print(f'the number is: {n}')

the number is: 3


## Review of NumPy Arrays

In [17]:
import numpy as np

a = np.array([3,4,0,0,-99999,0,1,5,0,5])
a

array([     3,      4,      0,      0, -99999,      0,      1,      5,
            0,      5])

In [18]:
a.shape=(2,5)
a

array([[     3,      4,      0,      0, -99999],
       [     0,      1,      5,      0,      5]])

In [19]:
row = a[0,:]    #index 0 row, all cols
row

array([     3,      4,      0,      0, -99999])

In [21]:
mask = row>-1   # make a boolean mask to remove all values that are less than -1
mask

array([ True,  True,  True,  True, False])

In [22]:
row = row[mask]
row

array([3, 4, 0, 0])

In [23]:
np.mean(row)

1.75

In [24]:
np.median(row)

1.5

In [26]:
locs_for_0 = np.where(row==0)
locs_for_0

(array([2, 3], dtype=int64),)

In [30]:
locs_for_0[0]

array([2, 3], dtype=int64)

In [32]:
locs_for_0[0].size

2

In [33]:
locs_for_non_0 = np.where(row != 0)
locs_for_non_0

(array([0, 1], dtype=int64),)

In [34]:
locs_for_non_0[0]

array([0, 1], dtype=int64)

In [35]:
locs_for_non_0[0].size

2

In [36]:
mask_for_non_0 = row>0
mask_for_non_0

array([ True,  True, False, False])

In [39]:
row_only_pos = row[mask_for_non_0]
row_only_pos

array([3, 4])

In [40]:
np.mean(row_only_pos)

3.5

### Check if a file is in the same directory as the Jupyter notebook

In [43]:
#check to see if weather_data.xlsx is in the same directory as the running Jupyter notebook
%ls    

 Volume in drive C is Windows
 Volume Serial Number is B899-AB94

 Directory of C:\Users\student\Desktop

10/09/2019  09:42 AM    <DIR>          .
10/09/2019  09:42 AM    <DIR>          ..
10/09/2019  09:14 AM    <DIR>          .ipynb_checkpoints
10/09/2019  09:11 AM             1,457 Kaltura Capture.lnk
10/09/2019  09:42 AM            10,365 Lab3_notes.ipynb
05/13/2016  01:33 PM               210 MSDS Online.url
08/01/2018  04:14 PM    <DIR>          Safety Information
10/09/2019  09:37 AM            10,204 weather_data.xlsx
               4 File(s)         22,236 bytes
               4 Dir(s)  322,178,961,408 bytes free
