# Week 3 Lab 3 Notes

## Printing out the value of a variable in Python

### Combining strings to print out the value of a variable

In [1]:
n = 3
str1 = 'The number is: '
str2 = str(n)
str3 = str1 + str2
print(str3)

The number is: 3


### Use multiple arguments passed to the print() function

In [2]:
n = 3
str1 = 'The number is:'
print(str1, n)            # two arguments passed to print()

The number is: 3


### Use Python f-strings to print out the value of a variable

In [3]:
n = 3
print('The number is n')

The number is n


In [4]:
print(f'The number is {n}')

The number is 3


In [5]:
print('The number is {n}')

The number is {n}


## Review of NumPy Arrays

In [6]:
import numpy as np

a = np.array([2,5,0,-9999,0,1,0,8])
a.shape = (2,4)   # reshape to 2 rows, 4 cols
a

array([[    2,     5,     0, -9999],
       [    0,     1,     0,     8]])

In [7]:
# all the values from 1st column
a[:,0]

array([2, 0])

In [8]:
# all the values from the 2nd row
a[1,:]

array([0, 1, 0, 8])

In [9]:
row0 = a[0,:]
row0

array([    2,     5,     0, -9999])

In [11]:
# how many zeros in row0?
mask = row0==0
mask

array([False, False,  True, False])

In [12]:
zeros = row0[mask]
zeros

array([0])

In [13]:
zeros.size

1

In [19]:
# remove the -9999
mask2 = row0 >= 0
mask2

array([ True,  True,  True, False])

In [20]:
row0_no_neg = row0[mask2]
row0_no_neg

array([2, 5, 0])

In [21]:
# statistics in NumPy
np.mean(row0_no_neg)

2.3333333333333335

In [22]:
np.max(row0_no_neg)

5

## NumPy's np.where()

### np.where() returns the locations of values in an array based on a logical condition

In [24]:
row0

array([    2,     5,     0, -9999])

In [26]:
locs = np.where(row0==5)
locs

(array([1], dtype=int64),)

In [27]:
type(locs)

tuple

In [28]:
# how many elements in the locs tuple?
len(locs)

1

In [29]:
locs[0]

array([1], dtype=int64)

In [30]:
type(locs[0])

numpy.ndarray

In [31]:
# find the number of elements which are 0
locs[0].size

1

In [32]:
# return the locations of elements which are 0
locs[0][:]

array([1], dtype=int64)

In [33]:
print(locs[0][:])

[1]


## How to bring an external data file into a Jupyter notebook

Move the external data file into the same directory (folder) as the Jupyter notebook.

In [34]:
# confirm the external data file is in the same directory as the Jupyter notebook
%ls

 Volume in drive C is Windows
 Volume Serial Number is B899-AB94

 Directory of C:\Users\student\Desktop

10/10/2019  01:38 PM    <DIR>          .
10/10/2019  01:38 PM    <DIR>          ..
10/10/2019  01:10 PM    <DIR>          .ipynb_checkpoints
10/10/2019  01:05 PM             1,457 Kaltura Capture.lnk
05/13/2016  01:33 PM               210 MSDS Online.url
08/01/2018  04:14 PM    <DIR>          Safety Information
10/10/2019  01:38 PM            10,143 weather_data.xlsx
10/10/2019  01:36 PM            11,517 week3_lab3_notes.ipynb
               4 File(s)         23,327 bytes
               4 Dir(s)  322,166,067,200 bytes free


In [36]:
import numpy as np
import pandas as pd

df = pd.read_excel('weather_data.xlsx', header=None)
df

0    1    2   3    4    5   6   7   8    9   ...    21  22   23   24  \
0     0    0  272   0    0    0   0   9  26    1  ...     1  15  224    0   
1    61  103    0   2    0    0   0   2   0   68  ...     0   0    5    0   
2     2    0   17  27    0   10   0   0  30   25  ...    26   0    0    9   
3   260    1    0   0    0    1   3   0   5    0  ...     0   0    0    0   
4    47    0    0   0    5  115  49  81   0    0  ...     0   0    0    0   
5     0    0   30  42    0    0   0   0   0    0  ...     0   2    2  240   
6     0    0    0   0    0    0   0   7   0    0  ...     0   0    0   10   
7     0   45    0   0    0    0   0   0   5    0  ...     0   0  158   62   
8     0    0    0   0    0    0   0   0   0    0  ...    37   0    0    0   
9     0    0    0  14  156    0   0   0   0  110  ...     0   0    0    0   
10    1  163    5   0    0    0   0   0   0    0  ...     0   2    2   10   
11    0    0    0   0    0   45   0   0   0   15  ...    34   0    0    0   

     25  26   27     28     29     30  
0     0   0    0      0     33     33  
1     0   0   62 -99999 -99999 -99999  
2     6  78    0      5      8      0  
3     9  35   13     86      0 -99999  
4     0   2    0      0      0      0  
5    16  35   14     14      8 -99999  
6     0   0    5      0      0      0  
7     1   0    0      0      0      0  
8     0   6  138     58     10 -99999  
9     0   0    0      0      0      1  
10  255   2    0      0      0 -99999  
11    0   0    0      0      0      0  

[12 rows x 31 columns]