# Week 3 Notes: NumPy and Arrays

### Built-in Functions don't need to be imported

In [1]:
l = [1,'two',3.0]
len(l)             #len() is built-in

3

### Some functions are part of the Python Standard Library, but not built-in and need to be imported to use

In [2]:
sin(l[2])           # sin() must be imported from the math module before it can be used

NameError: name 'sin' is not defined

In [3]:
from math import sin

sin(l[2])

0.1411200080598672

In [4]:
import math

math.sin(l[2])

0.1411200080598672

In [5]:
import math as ma

ma.sin(l[2])

0.1411200080598672

In [6]:
import statistics as st

st.mean(l[0:3:2])

2.0

## NumPy and Arrays

In [7]:
import numpy as np

np.__version__

'1.15.1'

In [8]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
l = [1,2.0,3+0j]
l

[1, 2.0, (3+0j)]

In [10]:
a = np.array([1,2.0,3+0j])
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
b = np.array([True,False,True])
b

array([ True, False,  True])

In [12]:
c = np.array(['my','string','array'])
c

array(['my', 'string', 'array'], dtype='<U6')

### Data Types in NumPy Arrays

most precise

 * np.bool_
 * np.int64
 * np.float64
 * np.sting_
 * np.object
 
least precise

NumPy arrays are "downcast" to the least precise data type, so that all of the elements in an array contain the same data type

In [13]:
s = np.array([True, 1, 'Oh my'])
s

array(['True', '1', 'Oh my'], dtype='<U11')

In [14]:
a = np.array([1,3.0,4.0], dtype=np.int64)
a

array([1, 3, 4], dtype=int64)

In [15]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [16]:
a.ndim

1

In [17]:
a.shape

(3,)

In [18]:
a.size

3

In [19]:
a = np.array([1.0,2.0,3.0])
a.dtype=np.int64
a

array([4607182418800017408, 4611686018427387904, 4613937818241073152],
      dtype=int64)

In [20]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
a.shape

(9,)

In [22]:
a.shape = (3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
a.shape

(3, 3)

In [24]:
a.ndim

2

In [25]:
a = np.ones(8)
a

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
a = np.zeros(8)
a

array([0., 0., 0., 0., 0., 0., 0., 0.])

## NumPy Functions are broadcast accross arrays

In [27]:
l = [1,4,16]
l*2

[1, 4, 16, 1, 4, 16]

In [28]:
a = np.array([1,4,16])
a*2

array([ 2,  8, 32])

In [29]:
a - 1

array([ 0,  3, 15])

In [30]:
a + a

array([ 2,  8, 32])

In [31]:
a**(1/2)

array([1., 2., 4.])

In [32]:
l = [1,4,16]
from math import sqrt
sqrt(l)                # Python's square root function from the math module in the Standard Library does not work on lists or arrays

TypeError: must be real number, not list

In [33]:
import numpy as np

a = np.array([1,4,16])
np.sqrt(a)

array([1., 2., 4.])

In [34]:
np.exp(a)

array([2.71828183e+00, 5.45981500e+01, 8.88611052e+06])

In [35]:
np.mean(a)

7.0

In [36]:
np.median(a)

4.0

## Array Indexing and Slicing

In [37]:
s = 'a string'
l = [0,1,2]
print(s[3])
print(l[2])

t
2


In [38]:
print(s[2::2])
print(l[0::2])

srn
[0, 2]


In [39]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
a[2]        # index a 1D array

2

In [41]:
a[1:7:2]     #slice a 1D array

array([1, 3, 5])

### Index and Slice 2D Arrays

In [42]:
a = np.arange(9)
a.shape = (3,3)
a = a + 2
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [43]:
# get the value 9 out of the array
# 9 is in row 2 and col 1 (remember Python counting starts at zero)
a[2,1]             #[row, col]

9

In [44]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [45]:
# replace the value 7 with the value 70
a[1,2] = 70
a

array([[ 2,  3,  4],
       [ 5,  6, 70],
       [ 8,  9, 10]])

In [46]:
a

array([[ 2,  3,  4],
       [ 5,  6, 70],
       [ 8,  9, 10]])

In [47]:
# return the first two rows of array a (row 0 and row 1)
a[0:2:1,0:3:1]

array([[ 2,  3,  4],
       [ 5,  6, 70]])

In [48]:
a[:2,:]       # row: start=default,0 stop=2 (stop at index 1), count by=defaut,1    col: start=default,0, stop=default, end, count by=default,1

array([[ 2,  3,  4],
       [ 5,  6, 70]])

In [49]:
# return the last column of the array a
a[0:3:1,2]

array([ 4, 70, 10])

In [50]:
a[:,-1]        # all rows, last column

array([ 4, 70, 10])

In [51]:
a = np.arange(12)
a.shape = (3,4)
a = 2*a + 1
a

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [52]:
# slice out [3, 5] [11, 13]
a[0:2,1:3]

array([[ 3,  5],
       [11, 13]])

In [53]:
# slice out [21, 23]
a[2, 2:4]
a[-1, 2:4]
a[-1, 2:]

array([21, 23])

In [54]:
# slice out [1,9] [5,13]
a[0:2,0:3:2]

array([[ 1,  5],
       [ 9, 13]])

In [55]:
a

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [56]:
# pull out 11, 15, 21
indexes = np.array([[1, 3, 2],[1, 1, 2]])
indexes

array([[1, 3, 2],
       [1, 1, 2]])

In [57]:
a = np.arange(12)
a = a - 4
a

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [58]:
indexes = np.array([4, 1, -1])

In [59]:
a[indexes]

array([ 0, -3,  7])

In [60]:
print(a[4],a[1],a[-1])

0 -3 7


In [61]:
indexes = [3,1,2]
a[indexes]

array([-1, -3, -2])

## Array Broadcasting

In [62]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [63]:
b = np.array([0,2])
b.shape = (2,1)
b

array([[0],
       [2]])

In [64]:
a*b

array([[0, 0, 0],
       [2, 4, 6]])

In [65]:
# multiplication table

rows = np.arange(1,11)
rows

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
cols = np.arange(1,11)
cols.shape = (10,1)
cols

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [67]:
cols*rows

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

## Boolean Masks

In [68]:
a = np.array([-3, -2, -1, 0, 1, 2])

In [69]:
# pull out all the positive numbers (not zero)


In [70]:
mask = np.array([False, False, False, False, True, True])

In [71]:
a[mask]

array([1, 2])

In [72]:
mask = a>0
mask

array([False, False, False, False,  True,  True])

In [73]:
a[mask]

array([1, 2])

In [74]:
mask = a<0
mask

array([ True,  True,  True, False, False, False])

In [75]:
a[mask]

array([-3, -2, -1])

In [76]:
mask = a==0
mask

array([False, False, False,  True, False, False])

In [77]:
a[mask]

array([0])

In [78]:
a = np.arange(24)
a.shape=(4,6)
a = 0.5*a - 10
a

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5],
       [ -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5],
       [ -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5]])

In [79]:
# pull out all the positive values

mask = a>0
mask

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True]])

In [80]:
a[mask]

array([0.5, 1. , 1.5])

In [81]:
# pull out the negative values
mask = a<0
mask

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False]])

In [82]:
a[mask]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5])

In [84]:
mask1 = a<-8
a1 = a[mask1]
a1

array([-10. ,  -9.5,  -9. ,  -8.5])

In [85]:
mask2 = a>0.5
a2 = a[mask2]
a2

array([1. , 1.5])

In [86]:
a3 = np.array([a1,a2])
a3

array([array([-10. ,  -9.5,  -9. ,  -8.5]), array([1. , 1.5])],
      dtype=object)

In [87]:
a

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5],
       [ -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5],
       [ -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5]])

In [88]:
a>0

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True]])

In [89]:
locs = np.where(a>0)  # returns the locations of a logical condition being true in an array
locs

(array([3, 3, 3], dtype=int64), array([3, 4, 5], dtype=int64))

In [90]:
a[locs]               # returns the values at those locations

array([0.5, 1. , 1.5])

In [91]:
a = np.arange(-5,5)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [92]:
locs = np.where(a>0)                         # pull out the locations where a>0
locs

(array([6, 7, 8, 9], dtype=int64),)

In [93]:
a[locs]                                     # index out the values from the specified locations

array([1, 2, 3, 4])